language: php

php:
    - 5.3
    - 5.4

before_script:
    - git config --global user.name "Test User"
    - git config --global user.email test@example.com
    - composer self-update
    - composer install --dev
